name = "0-day-counter"
workers_dev = true
compatibility_date = "2022-05-03"

[[kv_namespaces]]
  binding = "TASK_STORAGE"
  id = "<YOUR_ID>"
  preview_id = "<YOUR_PREVIEW_ID>"

[vars]
USERNAME = "user"
PASSWORD = "pass"
